### ISSUE TITLE
Not able to see anything onto load of iss.html file

### ISSUE THREAD

**Issue by vishalbacancy** [beebotte/ISS-realtime-position#1]
When i try to load the html file it gives me following error
![screenshot from 2015-06-12 18 00 06](https://cloud.githubusercontent.com/assets/12778068/8130464/3d2573fc-1130-11e5-8bdc-90e6414d8f06.png)

can you assist to resolve this ?

**Comment by bachwehbi** [comment]
The re is absolutely no error there.

It is just that you are not receiving any ISS positions. I suspect you are not publishing the ISS position son your account. You need to use the Python source code (https://github.com/beebotte/ISS-realtime-position/blob/master/iss_position_pub.py) to publish ISS positions. Then your web page will be able to subscibe and receive the position stream. 

If you don't want to publish the positions, use the public stream with access key given at https://github.com/beebotte/ISS-realtime-position/blob/master/iss.html#L60

**Comment by vishalbacancy** [comment]
I am very sorry Bachwehbi but I am really new to this.

I am not able to understnad properly what you want to tell me. What I have performed is I have cloned this project in one of my directory and then I am changing access keys to what I have in my beebotte account. I have all files specified in this project properly but nothing is happening till now. I even have .py file but I am still not abkle to have any view. Can you help ?

**Comment by vishalbacancy** [comment]
I have configured Channel key and access key along with security key in python file and html file. I also created neew channel named "ISS" with resource "position" but still nothing happened.

**Comment by bachwehbi** [comment]
You need first to run the python script:

1 - insure you have python installed
2 - install python package manager (https://pip.pypa.io/en/latest/installing.html)
3 - install beebotte (`pip install beebotte`)
4 - install pyephem (`pip install pyephem`)

Now you can run the script 

```
python iss_position_pub.py
```

Your script will calculate the position of the ISS and publish it to Beebotte.

Now if you open the .html file you should receive the published positions and see them on google maps.

Please have a look at https://beebotte.com/tutorials/iss_realtime_position for further details

**Comment by vishalbacancy** [comment]
I am able to perform each and every steps you have mentioned and able to gather pieces to form a single picture and in terminal lati, longi is getting displayed but still.  html file is displaying no map at all. It is fully blank.

**Comment by vishalbacancy** [comment]
Thanks bachwehbi, 

I am able to see now.Thanks for your thorough help.
